//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Sizes = new HashSet<Size>();
            this.Carts = new HashSet<Cart>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> UPC_Code { get; set; }
        public Nullable<int> AmountSold { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Revenue { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
        public string Photo { get; set; }
    
        public virtual ProductType ProductType { get; set; }
        public virtual ICollection<Size> Sizes { get; set; }
        public virtual ICollection<Cart> Carts { get; set; }
    }
}
